from typing import overload
import datetime
EVERYTHING_ERROR_CREATETHREAD: int
EVERYTHING_ERROR_CREATEWINDOW: int
EVERYTHING_ERROR_INVALIDCALL: int
EVERYTHING_ERROR_INVALIDINDEX: int
EVERYTHING_ERROR_INVALIDPARAMETER: int
EVERYTHING_ERROR_INVALIDREQUEST: int
EVERYTHING_ERROR_IPC: int
EVERYTHING_ERROR_MEMORY: int
EVERYTHING_ERROR_REGISTERCLASSEX: int
EVERYTHING_OK: int
REQUEST_ATTRIBUTES: int
REQUEST_DATE_ACCESSED: int
REQUEST_DATE_CREATED: int
REQUEST_DATE_MODIFIED: int
REQUEST_DATE_RECENTLY_CHANGED: int
REQUEST_DATE_RUN: int
REQUEST_EXTENSION: int
REQUEST_FILE_LIST_FILE_NAME: int
REQUEST_FILE_NAME: int
REQUEST_FULL_PATH_AND_FILE_NAME: int
REQUEST_HIGHLIGHTED_FILE_NAME: int
REQUEST_HIGHLIGHTED_FULL_PATH_AND_FILE_NAME: int
REQUEST_HIGHLIGHTED_PATH: int
REQUEST_PATH: int
REQUEST_RUN_COUNT: int
REQUEST_SIZE: int
SORT_ATTRIBUTES_ASCENDING: int
SORT_ATTRIBUTES_DESCENDING: int
SORT_DATE_ACCESSED_ASCENDING: int
SORT_DATE_ACCESSED_DESCENDING: int
SORT_DATE_CREATED_ASCENDING: int
SORT_DATE_CREATED_DESCENDING: int
SORT_DATE_MODIFIED_ASCENDING: int
SORT_DATE_MODIFIED_DESCENDING: int
SORT_DATE_RECENTLY_CHANGED_ASCENDING: int
SORT_DATE_RECENTLY_CHANGED_DESCENDING: int
SORT_DATE_RUN_ASCENDING: int
SORT_DATE_RUN_DESCENDING: int
SORT_EXTENSION_ASCENDING: int
SORT_EXTENSION_DESCENDING: int
SORT_FILE_LIST_FILENAME_ASCENDING: int
SORT_FILE_LIST_FILENAME_DESCENDING: int
SORT_NAME_ASCENDING: int
SORT_NAME_DESCENDING: int
SORT_PATH_ASCENDING: int
SORT_PATH_DESCENDING: int
SORT_RUN_COUNT_ASCENDING: int
SORT_RUN_COUNT_DESCENDING: int
SORT_SIZE_ASCENDING: int
SORT_SIZE_DESCENDING: int
SORT_TYPE_NAME_ASCENDING: int
SORT_TYPE_NAME_DESCENDING: int
TARGET_MACHINE_ARM: int
TARGET_MACHINE_X64: int
TARGET_MACHINE_X86: int

def CleanUp(*args, **kwargs) -> Any: ...
def DeleteRunHistory(*args, **kwargs) -> Any: ...
def Exit(*args, **kwargs) -> Any: ...
def GetBuildNumber(*args, **kwargs) -> Any: ...
def GetLastError(*args, **kwargs) -> Any: ...
def GetMajorVersion(*args, **kwargs) -> Any: ...
def GetMatchCase(*args, **kwargs) -> Any: ...
def GetMatchPath(*args, **kwargs) -> Any: ...
def GetMatchWholeWord(*args, **kwargs) -> Any: ...
def GetMax(*args, **kwargs) -> Any: ...
def GetMinorVersion(*args, **kwargs) -> Any: ...
def GetNumFileResults(*args, **kwargs) -> Any: ...
def GetNumFolderResults(*args, **kwargs) -> Any: ...
def GetNumResults(*args, **kwargs) -> Any: ...
def GetOffset(*args, **kwargs) -> Any: ...
def GetRegex(*args, **kwargs) -> Any: ...
def GetReplyID(*args, **kwargs) -> Any: ...
def GetReplyWindow(*args, **kwargs) -> Any: ...
def GetRequestFlags(*args, **kwargs) -> Any: ...
def GetResultAttributes(index: int) -> int: ...
def GetResultDateAccessed(index: int) -> datetime.datetime: ...
def GetResultDateCreated(index: int) -> datetime.datetime: ...
def GetResultDateModified(index: int) -> datetime.datetime: ...
def GetResultDateRecentlyChanged(index: int) -> datetime.datetime: ...
def GetResultDateRun(index: int) -> datetime.datetime: ...
def GetResultExtension(index: int) -> str: ...
def GetResultFileListFileName(index: int) -> str: ...
def GetResultFileName(index: int) -> str: ...
def GetResultFullPathName(index: int, max_path_length: int = ...) -> str: ...
def GetResultHighlightedFileName(index: int) -> str: ...
def GetResultHighlightedFullPathAndFileName(index: int) -> str: ...
def GetResultHighlightedPath(index: int) -> str: ...
def GetResultListRequestFlags(*args, **kwargs) -> Any: ...
def GetResultListSort(*args, **kwargs) -> Any: ...
def GetResultPath(index: int) -> str: ...
def GetResultRunCount(index: int) -> int: ...
def GetResultSize(index: int) -> union_LARGE_INTEGER: ...
def GetRevision(*args, **kwargs) -> Any: ...
def GetRunCountFromFileName(filepath: str) -> int: ...
def GetSearch(*args, **kwargs) -> Any: ...
def GetSort(*args, **kwargs) -> Any: ...
def GetTargetMachine(*args, **kwargs) -> Any: ...
def GetTotFileResults(*args, **kwargs) -> Any: ...
def GetTotFolderResults(*args, **kwargs) -> Any: ...
def GetTotResults(*args, **kwargs) -> Any: ...
def IncRunCountFromFileName(filepath: str) -> int: ...
def IsAdmin(*args, **kwargs) -> Any: ...
def IsAppData(*args, **kwargs) -> Any: ...
def IsDBLoaded(*args, **kwargs) -> Any: ...
def IsFileResult(arg0: int) -> int: ...
def IsFolderResult(arg0: int) -> int: ...
def IsQueryReply(message: int, wparam: int, lparam: int, dwID: int) -> int: ...
def IsVolumeResult(arg0: int) -> int: ...
def Query(wait: bool = ...) -> None: ...
def RebuildDB(*args, **kwargs) -> Any: ...
def Reset(*args, **kwargs) -> Any: ...
def SaveDB(*args, **kwargs) -> Any: ...
def SaveRunHistory(*args, **kwargs) -> Any: ...
@overload
def SetMatchCase(enable: bool) -> None: ...
@overload
def SetMatchCase(enable: bool) -> None: ...
@overload
def SetMatchCase(*args, **kwargs) -> Any: ...
def SetMatchPath(enable: bool) -> None: ...
def SetMatchWholeWord(enable: bool) -> None: ...
def SetMax(max: int) -> None: ...
def SetOffset(offset: int) -> None: ...
def SetReplyID(reply_id: int) -> None: ...
def SetReplyWindow(reply_window_handle: HWND__) -> None: ...
def SetRequestFlags(request_flags: int) -> None: ...
def SetRunCountFromFileName(filepath: str, runCount: int) -> int: ...
def SetSearch(search_string: str) -> None: ...
def SetSort(sort_mode: int) -> None: ...
def SortResultsByPath(*args, **kwargs) -> Any: ...
def UpdateAllFolderIndexes(*args, **kwargs) -> Any: ...
